# Generated by Django 3.2.4 on 2021-11-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_price', models.CharField(max_length=10)),
                ('dish_type', models.CharField(max_length=50)),
            ],
        ),
    ]
