# Generated by Django 3.2.4 on 2021-11-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='members',
            field=models.IntegerField(default=None, max_length=2),
        ),
    ]
