# Generated by Django 3.2.4 on 2021-11-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0005_auto_20211117_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
