# Generated by Django 3.2.4 on 2021-11-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
